### Question 2

In [ ]:
from sklearn.metrics import precision_score, accuracy_score
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn import datasets

## Preprocessing

In [ ]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split

# Load the Iris dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target

scaler = MinMaxScaler()
X = scaler.fit_transform(X)

# One-hot encode the labels
one_hot_y = np.zeros((y.shape[0], 3))
one_hot_y[np.arange(y.shape[0]), y] = 1

# y = np.eye(3)[y]

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, one_hot_y, test_size=0.2)

# Define the number of neurons in each layer
input_size = 4
hidden1_size = 4
hidden2_size = 5
output_size = 3

## Using Tanh Activation

In [ ]:
# Initialize the weights randomly
W1 = np.random.randn(input_size, hidden1_size)
W2 = np.random.randn(hidden1_size, hidden2_size)
W3 = np.random.randn(hidden2_size, output_size)

# Define the learning rate
learning_rate = 0.1

# Define the tanh function
def tanh(x):
    return np.tanh(x)

# Define the tanh derivative function
def tanh_derivative(x):
    return 1 - (np.tanh(x)**2)

# Define the cross-entropy loss function
def cross_entropy(y_pred, y_true):
    return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))

# Perform backpropagation for 15 iterations
for i in range(15):
    # Forward pass
    z1 = X_train @ W1
    a1 = tanh(z1)
    z2 = a1 @ W2
    a2 = tanh(z2)
    z3 = a2 @ W3
    y_pred = tanh(z3)

    # Compute the loss
    loss = cross_entropy(y_pred, y_train)

    # Backward pass
    dz3 = y_pred - y_train
    dw3 = a2.T @ dz3
    dz2 = dz3 @ W3.T * tanh_derivative(a2)
    dw2 = a1.T @ dz2
    dz1 = dz2 @ W2.T * tanh_derivative(a1)
    dw1 = X_train.T @ dz1

    # Update the weights
    W1 -= learning_rate * dw1
    W2 -= learning_rate * dw2
    W3 -= learning_rate * dw3

    # Training Accuracy
    predictions = np.argmax(y_pred, axis=1)
    y_train_labels = np.argmax(y_train, axis=1)
    accuracy = (predictions == y_train_labels).mean()

    # Test Forward Pass
    # Forward pass
    z1 = X_test @ W1
    a1 = tanh(z1)
    z2 = a1 @ W2
    a2 = tanh(z2)
    z3 = a2 @ W3
    y_pred_test = tanh(z3)

    # Testing Accuracy
    predictions_test = np.argmax(y_pred_test, axis=1)
    y_test_labels = np.argmax(y_test, axis=1)
    accuracy_test = (predictions_test == y_test_labels).mean()

    print(f"Epoch {i+1}:")
    print("Train accuracy: {:.2f}%".format(accuracy * 100))
    print("Test accuracy: {:.2f}%".format(accuracy_test * 100))

Epoch 1:
Train accuracy: 31.67%
Test accuracy: 43.33%
Epoch 2:
Train accuracy: 49.17%
Test accuracy: 20.00%
Epoch 3:
Train accuracy: 36.67%
Test accuracy: 43.33%
Epoch 4:
Train accuracy: 30.83%
Test accuracy: 20.00%
Epoch 5:
Train accuracy: 36.67%
Test accuracy: 43.33%
Epoch 6:
Train accuracy: 30.83%
Test accuracy: 20.00%
Epoch 7:
Train accuracy: 36.67%
Test accuracy: 36.67%
Epoch 8:
Train accuracy: 32.50%
Test accuracy: 43.33%
Epoch 9:
Train accuracy: 30.83%
Test accuracy: 43.33%
Epoch 10:
Train accuracy: 30.83%
Test accuracy: 36.67%
Epoch 11:
Train accuracy: 32.50%
Test accuracy: 36.67%
Epoch 12:
Train accuracy: 32.50%
Test accuracy: 20.00%
Epoch 13:
Train accuracy: 36.67%
Test accuracy: 36.67%
Epoch 14:
Train accuracy: 32.50%
Test accuracy: 20.00%
Epoch 15:
Train accuracy: 36.67%
Test accuracy: 36.67%


<ipython-input-3-7f448e30324d>:19: RuntimeWarning: invalid value encountered in log
  return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))
<ipython-input-3-7f448e30324d>:19: RuntimeWarning: divide by zero encountered in log
  return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))
<ipython-input-3-7f448e30324d>:19: RuntimeWarning: invalid value encountered in multiply
  return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))


### Question 1

In [ ]:
from sklearn.metrics import precision_score, accuracy_score
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn import datasets

In [ ]:


# importing and loading the IRIS dataset
iris = datasets.load_iris()
X = iris.data # features
y = iris.target # target

X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
# Scaling the data for improving upon the accuracy
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

X

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [ ]:
# doing one hot encoding
one_hot_y = np.zeros((y.shape[0], 3))
one_hot_y[np.arange(y.shape[0]), y] = 1

# tts
X_train, X_test, y_train, y_test = train_test_split(X, one_hot_y, test_size=0.2)

In [ ]:
# assigning random weight and bias
weights = np.random.rand(4, 3)
bias = np.random.rand(1, 3)

learning_rate = 0.1

# backpropagation for 2 iterations
for _ in range(2):
    # forward pass
    output = np.dot(X_train, weights) + bias
    output = np.maximum(0, output)  # ReLU activation function
    output = np.exp(output) / np.sum(np.exp(output), axis=1, keepdims=True)  # Softmax function
    
    # Compute the loss (cross-entropy)
    loss = -np.mean(y_train * np.log(output))
    print("Loss:", loss)

    # Compute the gradients
    error = output - y_train
    weights_grad = np.dot(X_train.T, error)
    bias_grad = np.sum(error, axis=0, keepdims=True)

    # Update the trainable parameters
    weights -= learning_rate * weights_grad
    bias -= learning_rate * bias_grad

# testing the model
output = np.dot(X_test, weights) + bias
output = np.maximum(0, output)  # ReLU activation function
output = np.exp(output) / np.sum(np.exp(output), axis=1, keepdims=True)  # Softmax function for output layer
y_pred = np.argmax(output, axis=1)

# Compute the accuracy of the model

accuracy = np.mean(y_pred == np.argmax(y_test, axis=1))
print("Accuracy:", accuracy)


Loss: 0.3561151506391446
Loss: 0.28916319563704523
Accuracy: 0.6666666666666666
